# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mi-Log' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mi-Log
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'Mi-LogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Mi-LogUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
